### ISSUE TITLE
Game Randomly Crashing Trying To Render Axolotls?[BUG]

### ISSUE THREAD

**Issue by LadyKatieSue** [theomenden/OmenCraft#10]
**Describe the bug**
While I am exploring a lush cave, my game keeps randomly crashing & Majong gives me this error code:

"The game crashed whilst rendering entity in world
Error: net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: textures/entity/axolotl/axolotl_mavm:white.png

Exit Code: -1"

This code has ended with white.png, black.png, lucia.png, & golden.png. This has happened 5 times now in the past 2 days, ever since I updated to the newest release of the mod pack.

**To Reproduce**
1. Explore area with axolotls?

**Expected behavior**
Exploration without random crashing lol

**Environment**
Omen Craft: 0.12.031 (also happens with 0.12.03)
Minecraft version: 1.19.2
Operating System: Windows 10 (amd64) version 10.0

**Additional context**
Crash Reports Generated:

[crash-2022-12-07_00.10.40-client.txt](https://github.com/theomenden/OmenCraft/files/10173635/crash-2022-12-07_00.10.40-client.txt)
[crash-2022-12-07_00.05.25-client.txt](https://github.com/theomenden/OmenCraft/files/10173636/crash-2022-12-07_00.05.25-client.txt)
[crash-2022-12-06_23.46.15-client.txt](https://github.com/theomenden/OmenCraft/files/10173638/crash-2022-12-06_23.46.15-client.txt)
[crash-2022-12-06_15.09.11-client.txt](https://github.com/theomenden/OmenCraft/files/10173639/crash-2022-12-06_15.09.11-client.txt)

**Comment by AluTheCrow** [comment]
Reviewing.

**Comment by AluTheCrow** [comment]
Fixed in the latest version (actually was fixed earlier, but I'm silly and forgot to update)

Fix - removed the mod
