### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CamoToothless** [theomenden/OmenCraft#12]
To help you resolve your issue faster please make sure you have done the following:

* Searched existing issues (even closed ones) for your same problem.
* Make sure you have installed the required dependencies listed on the readme.

---
name: Overworld Lag c/w Nether Entry
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''AlucardMG36

---
*Some things that really help get your issue resolved faster are:*

**Describe the bug**

--when someone enters the nether, the overworld begins to lag: chunks begin to not load, if people are in boats they deboat or can't exit the boat, no blocks can be broken or open chests. The only way to "correct" the issue is to disconnect from the server and rejoin with some chunks loaded in, but not all

**To Reproduce**
1. Have someone go into the nether

**Expected behavior**
-can't go anywhere (stuck in one specific chunk that's loaded in)

**Environment**
A concise description of your environment: Omen Craft version,
Minecraft version, Fabric API, operating system, etc.
--omen craft

**Additional context**
--some individuals have stated that no lag appears on their end when inside the nether
--appears to happen to specific people in the overworld (I have personally checked if my modpack is updated and it is)

Thanks!

***P.S. If it doesn't look like you read the above then your issue will likely be closed without further explanation.***
![huge_2023-03-22_20 16 37](https://user-images.githubusercontent.com/128660695/227084106-23bbe8df-dcbf-4887-bfd9-d1a076661fbd.png)
![huge_2023-03-22_20 16 28](https://user-images.githubusercontent.com/128660695/227084116-5187c002-6171-4cfa-8f80-55adbb007eef.png)

**Comment by AluTheCrow** [comment]
Reviewing.
Note: This may be a server issue, as I can't recreate it currently on my servers.

**Comment by AluTheCrow** [comment]
Resolved in this next version.
