### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gaywitchcryptid** [theomenden/OmenCraft#3]
To help you resolve your issue faster please make sure you have done the following:

* Searched existing issues (even closed ones) for your same problem.
* Make sure you have installed the required dependencies listed on the readme.

---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---
*Some things that really help get your issue resolved faster are:*

**Describe the bug**

**To Reproduce**
1. <!-- Replace this text --!>
2. <!-- Replace this text --!>

**Expected behavior**

**Environment**
A concise description of your environment: Omen Craft version,
Minecraft version, Fabric API, operating system, etc.

**Additional context**

Thanks!

***P.S. If it doesn't look like you read the above then your issue will likely be closed without further explanation.***

Username Gaywitchcryptid

Running OmenCraft on Cursedforge at 10080MB, 9056MB, and 8064MB
Ram usage spikes to 92% memory usage, game causes my computer to green screen after a few minutes of play, despite adjustments to memory allocation. I have run other games to see if this is a computer issue or a minecraft issue and the green screen only happens with Omencraft.

Only running Discord actively in the background (no voice calls, streaming, or video calls going on; only chat)

Computer specs are:

Device name	DESKTOP-J7FM7RJ
Processor	Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz
Installed RAM	16.0 GB
Device ID	F47DACE0-3F41-4255-83AB-4F0C2CF6643B
Product ID	00326-10060-56298-AA596
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support

Window specs are:

Edition	Windows 10 Home
Version	21H2
Installed on	‎3/‎18/‎2021
OS build	19044.2251
Experience	Windows Feature Experience Pack 120.2212.4180.0

Feel free to PM me on discord if you need any more information.

**Comment by AluTheCrow** [comment]
Reviewing

**Comment by AluTheCrow** [comment]
Latest pack update should help alleviate this issue - we've been working on settings to get RAM usage down below 8gb. 

So far, we've gotten it to 8gb, but aim to go less.
