### ISSUE TITLE
Mo Fuggin Mo Fugga mah shiuut done broke nawt enuf ram to save mah compy

### ISSUE THREAD

**Issue by BoostedBreadTrash** [theomenden/OmenCraft#4]
Loading the modpack up I noticed the loading bar filled almost entirely up to 8gb when attempting to load all of the packs. This is the 3rd time I've loaded this pack and can say it loaded significantly faster this time. I attempted to load into the server and OpenJDK just stops responding. It loads in, albeit with some freezes and lag at first, with 16gb of ram just fine. I am doing nothing else but chatting on discord and listening to spotify as well as watching the server on Chrome. Neither lag out while MC dies trying to load in the server. Here's my screen while loading into the server
![Screenshot (414)](https://user-images.githubusercontent.com/102133216/201436733-b8be4127-2765-4329-a23b-36bcaeb87664.png)

**Comment by AluTheCrow** [comment]
Reviewing

**Comment by AluTheCrow** [comment]
This should be better in the latest version of the pack. 

Will continue to monitor, especially for server side use.
