### ISSUE TITLE
Minecraft Crash Upon Using Alloy Forge Mod [BUG]

### ISSUE THREAD

**Issue by LadyKatieSue** [theomenden/OmenCraft#6]
**Description**
I attempted to use the multiforge that combines multiple metals to create stronger ingots from the Alloy Forge mod. But after building the forge, every time I right click on it to open/use it, I'm immediately taken to a saving/loading screen, & then very briefly to a "minecraft has crashed" screen with a link to the crash report that closes before I can open the link. Instead of letting me go back to the title screen, it closes itself out completely & has to be restarted from CurseForge. I have tried this on both multiplayer & single player, & the result is the same.

**To Reproduce**
1. Build a forge controller, then a full sized forge according to Alloy Forge's blueprint.
2. Right click on forge controller.

**Expected behavior**
Opening the forge in order to place multiple ores inside to create new, stronger metal.

**Environment**
Omen Craft version: 0.11.14
Minecraft version: 1.19.2
Operating System: Windows 10 (amd64) version 10.0

Crash log: 
[crash-2022-11-21_20.45.02-client.txt](https://github.com/theomenden/OmenCraft/files/10064786/crash-2022-11-21_20.45.02-client.txt)

**Comment by AluTheCrow** [comment]
This has been fixed in the 0.11.2219 update.

Will continue to monitor as time goes on.
