### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PokeyNBrown** [theomenden/OmenCraft#7]
To help you resolve your issue faster please make sure you have done the following:

* Searched existing issues (even closed ones) for your same problem.
* Make sure you have installed the required dependencies listed on the readme.

---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---
*Some things that really help get your issue resolved faster are:*

**Describe the bug**

**To Reproduce**
1. <!-- Replace this text --!>
2. <!-- Replace this text --!>

**Expected behavior**

**Environment**
A concise description of your environment: Omen Craft version,
Minecraft version, Fabric API, operating system, etc.

**Additional context**

Thanks!

***P.S. If it doesn't look like you read the above then your issue will likely be closed without further explanation.***
[latest.log](https://github.com/theomenden/OmenCraft/files/10072934/latest.log)

**Comment by AluTheCrow** [comment]
Please provide any details in future bugs.
