### ISSUE TITLE
[BUG] Persistent transparent block textures

### ISSUE THREAD

**Issue by forcesinbalance** [theomenden/OmenCraft#8]
Block textures failed to render for multiple entire chunks. Blocks in the affected chunks remain transparent across multiple exits and re-launches. Java binary shows unusually high RAM usage (over 10Gb, when only 9Gb is allocated to the game).

**To Reproduce**
Uncertain. The affected chunks previously rendered normally, and attempts to correct two affected chunks by removing or changing blocks called out by errors in the log were ineffective. Logs and testing indicate that it is related to BlockState culling in Sodium, but I haven't figured out what's triggering it.

**Workaround**
In the near term, turning off BlockState Culling in Options->Video Settings->More Culling will cause the affected chunks to render normally. However, it will probably cause a performance hit and does not address the excess memory load that seems to accompany the issue.

**Environment**
Omen Craft version: v0.11.2219-hf
Fabric loader: 0.14.10-1.19.2, launched from vanilla MC launcher
9Gb RAM allocated in launch parameters.
Windows 10

**Attachments**
I have attached screenshots showing the rendering issue as well as the high memory usage. 
I have attached a number of logfiles reflecting various things I tested. Log 5 is likely of most interest, as it shows disabling and reactivating the setting that affects the chunk visibility.
[5-RenderBugDeactivateAndReactivateBlockStateCulling.log](https://github.com/theomenden/OmenCraft/files/10097287/5-RenderBugDeactivateAndReactivateBlockStateCulling.log)
[1-ChunkRenderingBug.log](https://github.com/theomenden/OmenCraft/files/10097288/1-ChunkRenderingBug.log)
[2-ChunkRenderBirchGateError.log](https://github.com/theomenden/OmenCraft/files/10097289/2-ChunkRenderBirchGateError.log)
[3-ChunkRenderBugWithReplacedGates.log](https://github.com/theomenden/OmenCraft/files/10097290/3-ChunkRenderBugWithReplacedGates.log)
[4-ChunkRenderBugWhileTraveling.log](https://github.com/theomenden/OmenCraft/files/10097291/4-ChunkRenderBugWhileTraveling.log)
![2022-11-26_14 34 03](https://user-images.githubusercontent.com/57429312/204114109-348a4b3f-de21-4221-867a-b7b5f52daed8.png)
![RenderBugMemoryStateScreenshot](https://user-images.githubusercontent.com/57429312/204114111-cdf8fc9e-eb4a-41fa-a9d3-e109b656c459.png)

**Comment by AluTheCrow** [comment]
I've been unable to reproduce this bug - but I will keep trying. 

The memory usage is more of a concern for me. 
Most likely due to me pushing up the modpack without actually resetting from the test environment configs.

**Comment by AluTheCrow** [comment]
Downloaded The modpack on a significantly less powerful machine

Specifically, my cousin's laptop -
i5-9600
12gb ddr4 2666mhz
1tb M.2 nvme
Rtx 2060

This was a fresh and "sealed" download, where the only thing I changed was the amount of RAM that could be dedicated to Minecraft and by extension, the JVM. The Block State Culling and all sodium settings remained AS IS from the fresh install. 

Results so far:
Ran smoothly at 60fps with 8gb of RAM max given to the JVM - very little-no stuttering. No issues with invisible chunks, and was able to keep RAM at 87-94% usage.

Afterthoughts:
Now, obviously this isn't great, and I KNOW these issues exist, but I'm trying to find the pattern here. This is just particularly strange behavior to see, and I'm wondering what the context is. Granted- I launched the game from the curseforge launcher, then from prism Launcher, and finally the vanilla launcher.

These issues require further experimentation so I can reproduce them, and move onto a more optimal, streamlined, and accessible pack.

**Comment by AluTheCrow** [comment]
This is caused on some machines using the block state culling option in More Culling under sodium - you should be able to just unclick the box and it'll still work. 

We've also removed the problematic mods causing a lot of issues with RAM.
